version: "3.9"

services:
  api:
    container_name: api_kenzie_moveis
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db_kenzie
      - DB_PASSWORD=1234
      - DB=kenzie_moveis
      - DB_USER=kenzie_moveis
      - DB_PORT=5432
      - SECRET_KEY=sua_chave_secreta
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db_kenzie
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=kenzie_moveis
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kenzie_moveis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gustavo -d kenzie_moveis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
